; Script generated by the Inno Script Studio Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "余氏中文輸入法"
#define MyAppVersion "64bits windows 10 (20171025 廣東話簡體版)"
#define MyAppPublisher "Edward Yu"
#define MyAppURL "https://user.qzone.qq.com/1449059993/blog/1508991831"
#define MyAppExeName "MyProg.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{8760ED57-DDBB-4A2D-B090-97249D3E4AAF}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
CreateAppDir=no
OutputBaseFilename=setupSimyu64
Compression=lzma
SolidCompression=yes
AlwaysRestart=yes
ArchitecturesInstallIn64BitMode=x64
ArchitecturesAllowed=x64

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "C:\edward\eykmime\simyu64\simyu32.exe"; DestDir: "{win}"; Flags: ignoreversion
Source: "C:\edward\eykmime\simyu64\copysim.bat"; DestDir: "{win}"; Flags: ignoreversion
Source: "C:\edward\eykmime\simyu64\miniime.tpl"; DestDir: "{win}"; Flags: ignoreversion
Source: "C:\edward\eykmime\simyu64\simyu.IME"; DestDir: "{win}"; Flags: ignoreversion
Source: "C:\edward\eykmime\simyu64\simyu.reg"; DestDir: "{win}"; Flags: ignoreversion
Source: "C:\edward\eykmime\simyu64\simyusim.reg"; DestDir: "{win}"; Flags: ignoreversion
Source: "C:\edward\eykmime\simyu64\simyu.TBL"; DestDir: "{win}"; Flags: ignoreversion
Source: "C:\edward\eykmime\simyu64\simyuPHR.TBL"; DestDir: "{win}"; Flags: ignoreversion
Source: "C:\edward\eykmime\simyu64\simyuPTR.TBL"; DestDir: "{win}"; Flags: ignoreversion
Source: "C:\edward\eykmime\simyu64\UIMETOOL.exe"; DestDir: "{win}"; Flags: ignoreversion
Source: "C:\edward\eykmime\simyu64\UNIIME.DLL"; DestDir: "{win}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files
[Run]
Filename: "{app}\copysim.bat"
